{
  context.stopProcess();
  if (!unloggedExceptionClasses.contains(th.getClass().getName())) {
    LOG.error("An error occurred during the workflow",th);
  }
  throw new WorkflowException(th);
}
